// Writes next/.env.development.local from the running local Supabase (`npm run db:start` first).
import { execSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

let out
try {
  out = execSync('npx --yes supabase --workdir .. status -o env', { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] })
} catch (e) {
  console.error('Could not read the local Supabase status. Is it running? Try: npm run db:start\n' + (e.stderr || e.message))
  process.exit(1)
}

const env = Object.fromEntries(
  out.split('\n').map(l => l.match(/^([A-Z_]+)="?(.*?)"?$/)).filter(Boolean).map(m => [m[1], m[2]])
)
const url = env.API_URL
const key = env.ANON_KEY || env.PUBLISHABLE_KEY
if (!url || !key) {
  console.error('API_URL / ANON_KEY not found in `supabase status -o env`:\n' + out)
  process.exit(1)
}

const file = fileURLToPath(new URL('../.env.development.local', import.meta.url))
writeFileSync(file, `# generated by npm run db:env (local Supabase) - do not commit\n# Overrides .env.local during npm run dev; delete this file to go back to the hosted dev project.\nNEXT_PUBLIC_SUPABASE_URL=${url}\nNEXT_PUBLIC_SUPABASE_ANON_KEY=${key}\n`)
console.log(`wrote ${file}\n  NEXT_PUBLIC_SUPABASE_URL=${url}`)
