import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = { robots: { index: false, follow: false } }

export default function CompanyPage() {
  return (
<div className="min-h-screen bg-white font-['Noto_Sans_JP']"><div className="min-h-screen flex flex-col max-w-3xl mx-auto relative overflow-hidden">{/* Header */}<header className="pt-12 pb-8 px-4 flex items-center justify-between relative shrink-0"><Link className="p-2 hover:bg-gray-100 rounded-full transition-colors group z-10" href="/"><svg className="h-6 w-6 text-gray-400 group-hover:text-gray-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 19l-7-7 7-7" /></svg></Link><div className="absolute left-1/2 transform -translate-x-1/2"><img className="h-20 w-auto object-contain" src="/logo_irooto.png" alt="いろおと 絶対音感トレーニング" /></div><div className="w-10" />{' '}{/* Spacer */}</header><main className="flex-grow px-6 pb-20 overflow-y-auto"><div className="bg-gray-50 rounded-3xl p-8 border border-gray-100 shadow-sm"><div className="text-center mb-10"><h1 className="text-xs font-bold text-blue-500 uppercase tracking-[0.2em] mb-4">Company Info</h1><h2 className="text-2xl font-bold text-gray-900 mb-2">株式会社暁</h2><p className="text-xs text-gray-400 font-medium tracking-widest uppercase">Akatsuki Inc.</p></div><div className="space-y-6"><div className="border-b border-gray-100 pb-4"><p className="text-[10px] text-gray-400 uppercase tracking-widest mb-1">設立</p><p className="text-sm text-gray-700 font-bold leading-relaxed">2025年4月30日</p></div><div className="border-b border-gray-100 pb-4"><p className="text-[10px] text-gray-400 uppercase tracking-widest mb-1">資本金</p><p className="text-sm text-gray-700 font-bold leading-relaxed">300,000円</p></div><div className="border-b border-gray-100 pb-4"><p className="text-[10px] text-gray-400 uppercase tracking-widest mb-1">所在地</p><p className="text-sm text-gray-700 font-bold leading-relaxed">長野県長野市大字鶴賀緑町1418番地</p></div><div className="border-b border-gray-100 pb-4"><p className="text-[10px] text-gray-400 uppercase tracking-widest mb-1">代表者</p><p className="text-sm text-gray-700 font-bold leading-relaxed">司空 舜</p></div><div className="pb-4"><p className="text-[10px] text-gray-400 uppercase tracking-widest mb-1">事業内容</p><p className="text-sm text-gray-700 font-bold leading-relaxed">インターネットサービスの企画・開発・運営</p></div></div></div><div className="mt-12 space-y-4 text-center"><p className="text-xs text-gray-500 leading-relaxed">私たちは最新のテクノロジーを活用し、<br />「できた！」という喜びを創造します。</p></div></main><footer className="text-center text-gray-300 text-[10px] pb-8 shrink-0">&copy; 2026 Akatsuki Inc.</footer></div></div>
  )
}
